### ISSUE TITLE
couple of cppcheck issues

### ISSUE THREAD

**Issue by chipitsine** [vision5/ngx_devel_kit#14]
[src/ndk_regex.c:127]: (error) Uninitialized variable: n
[src/ndk_regex.c:189]: (error) Uninitialized variable: n

look weird, for loop with "n" undefined. I've no idea how to fix that.

**Comment by client9** [comment]
nice find @chipitsine 

`n` seems to only be set if `*a != NGX_CONF_UNSET_PTR` in the following code:

``` c
    if (*a != NGX_CONF_UNSET_PTR) {

        n = cf->args->nelts > 4 ? cf->args->nelts : 4;

        *a = ngx_array_create (cf->pool, n, sizeof (ngx_regex_elt_t));
        if (*a == NULL) {
            return  NGX_CONF_ERROR;
        }
    }
```

and as defined in `ngx_conf_file.h`

```
 #define NGX_CONF_UNSET_PTR   (void *) -1
```

**Comment by chipitsine** [comment]
ngx_devel_kit does not have any test, we still can add it to travis-ci, at least build + cppcheck
what do you think ?

**Comment by agentzh** [comment]
@chipitsine I prefer not.

**Comment by agentzh** [comment]
Personally I don't want to touch the NDK regex part since I only actually make use of the set_var subsystem. There is no easy way to test due to the lack of any tests exercising that part (while many of our nginx C modules cover the `set_var` NDK part).

**Comment by ghost** [comment]
It's been a while since I've looked at this code, but having quickly looked at the source, I'm fairly sure it should just be initialized to 0 (which I think is automatically done by compilers, but might throw warnings or errors depending on the compiler and/or options passed).

Just change:

ngx_uint_t i, n;

to

ngx_uint_t i, n=0;

Should fix it I think.

I'm busy with other stuff at the mo, and would want to test properly before committing - feel free to try that though.
