### ISSUE TITLE
ngx_devel_kit colliding with nginx-development-kit

### ISSUE THREAD

**Issue by jari-omniata** [vision5/ngx_devel_kit#21]
set-misc-nginx-module has dependency for ngx_devel_kit. In Ubuntu 16, there is already nginx-development-kit (https://github.com/protonet/nginx-debian/tree/master/modules/nginx-development-kit) installed, which collides badly.

Please clarify the difference between these two.

**Comment by agentzh** [comment]
@jari-omniata It seems that they are the same thing. No wonder they conflict. Ubuntu is notorious for renaming open source projects to something else in their packages.

**Comment by devzer01** [comment]
answering here if anyone else finds them in the same situation, 

```apt source libnginx-mod-http-ndk```

i try to use the ubuntu packaged version, however i am not sure what i must point at for the header reference, since the package does not include a dev package and it itself doesn't come with headers

**Comment by simpl** [comment]
Hi @devzer01,

What are you using the NDK for?

Probably the best thing to do is to download the OpenResty package, and use that for your goals, otherwise, use the OpenResty package as a guide for how to use the NDK.

The NDK does indeed contain headers, but you need to include them in the right way.

OpenResty does this correctly, and has some good docs on how to do so as well.

Best.
