### ISSUE TITLE
error=sizeof-pointer-memaccess

### ISSUE THREAD

**Issue by Temesta** [vision5/ngx_devel_kit#25]
I'm on ubuntu Bionic and tried to compile as static module. Configure works fine, but when compiling with make, I get this error  here ...

Using GCC-7 ... Same error with GCC-8

cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /home/maarten/src/nginx-1.14.0/addons/ngx_devel_kit/objs -I objs/addon/ndk -I objs -I src/http -I src/http/modules -I /usr/local/passenger-5.3.5/src -I /home/maarten/src/nginx-1.14.0/addons/ngx_devel_kit/src -I /home/maarten/src/nginx-1.14.0/addons/ngx_devel_kit/src -I /home/maarten/src/nginx-1.14.0/addons/ngx_devel_kit/objs -I objs/addon/ndk -I src/mail \
	-o objs/addon/src/ndk.o \
	/home/maarten/src/nginx-1.14.0/addons/ngx_devel_kit/src/ndk.c
In file included from src/core/ngx_core.h:50:0,
                 from /home/maarten/src/nginx-1.14.0/addons/ngx_devel_kit/src/ndk.h:12,
                 from /home/maarten/src/nginx-1.14.0/addons/ngx_devel_kit/src/ndk.c:6:
/home/maarten/src/nginx-1.14.0/addons/ngx_devel_kit/src/ndk_conf_file.c: In function 'ndk_replace_command':
/home/maarten/src/nginx-1.14.0/addons/ngx_devel_kit/src/ndk_string_util.h:13:66: error: argument to 'sizeof' in 'memcpy' call is the same pointer type 'ngx_command_t * {aka struct ngx_command_s *}' as the destination; expected 'ngx_command_t {aka struct ngx_command_s}' or an explicit length [-Werror=sizeof-pointer-memaccess]
 #define     ndk_memcpyp(d,s)                ngx_memcpy(d,s,sizeof(s))
                                                                  ^
src/core/ngx_string.h:104:59: note: in definition of macro 'ngx_memcpy'
 #define ngx_memcpy(dst, src, n)   (void) memcpy(dst, src, n)
                                                           ^
/home/maarten/src/nginx-1.14.0/addons/ngx_devel_kit/src/ndk_conf_file.c:389:17: note: in expansion of macro 'ndk_memcpyp'
                 ndk_memcpyp (cmd, new_cmd);
                 ^~~~~~~~~~~
cc1: all warnings being treated as errors
objs/Makefile:1434: recipe for target 'objs/addon/src/ndk.o' failed
make[1]: *** [objs/addon/src/ndk.o] Error 1
make[1]: Leaving directory '/home/maarten/src/nginx-1.14.0'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by simpl** [comment]
@Temesta - Sorry for not replying before.  I don't really maintain this these days, and hadn't seen your issue until now.

Did you get this sorted?  I don't think this is serious (the NDK has been used for about a decade now with few modifications, but it would be best to fix this), and you can just remove -Werror to stop turning warnings into errors, but I'll look into this in the next week or so and try to push a fix out so that doesn't happen.

**Comment by Temesta** [comment]
@mclyne Ok, no problem. Actually I don't remember how or whether I actually fixed this. But would be nice if you could update the code for other users.

**Comment by simpl** [comment]
@Temesta Agreed.  I'll let you know when it's fixed.

**Comment by simpl** [comment]
@Temesta OK, so after a long break from all this, I've now come back to tidying up a bunch of things, and I've looked into this again.

There's no issue here.  What happens is that -Werror turns warnings into errors.  If you remove -Werror (which is safe to do, since they're just warnings), you'll be fine.

You can see this showing up as [-Werror=sizeof-pointer-memaccess].

This is what I had assumed ages ago, but had been out of the programming scene for a while, and didn't want to say it wasn't an issue if it was.

Thanks for reporting it in the first place, and apologies for the very long delay in responding.  I'll go ahead and close this (finally).

**Comment by Temesta** [comment]
Ok, thanks for letting me know. This is really long time ago :)
So I don't remember the exact issue.

Best regards,

Maarten
