### ISSUE TITLE
nginx: [emerg] unknown directive "ELF" in ndk_http_module.so:4

### ISSUE THREAD

**Issue by svarlitskiy** [vision5/ngx_devel_kit#30]
Tried to compile and use on arch linux and I keep getting ' unknown directive "ELF" '. 

```sh
nginx -t

nginx: [emerg] unknown directive "ELF" in ndk_http_module.so:4
nginx: configuration file nginx.conf test failed
```

```sh
nginx -V

nginx version: nginx/1.21.1
built by gcc 11.1.0 (GCC) 
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
configure arguments: --prefix=~/nginx --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_secure_link_module --with-mail --with-mail_ssl_module --with-stream --with-stream_ssl_module --with-stream_realip_module --with-stream_geoip_module --with-compat --with-pcre=~/pkgs/pcre --with-pcre-jit --with-threads --with-zlib=~/pkgs/zlib --with-openssl=~/pkgs/openssl --add-dynamic-module=~/mods/ngx_devel_kit --add-dynamic-module=~/mods/ngx_http_auth_pam_module --add-dynamic-module=~/mods/ngx_brotli --add-dynamic-module=~/mods/ngx_dynamic_limit_req_module --add-dynamic-module=~/mods/ngx_cookie_limit_req_module --add-dynamic-module=~/mods/form-input-nginx-module --add-dynamic-module=~/mods/lua-nginx-module --add-dynamic-module=~/mods/lua-ssl-nginx-module --add-dynamic-module=~/mods/redis2-nginx-module --add-dynamic-module=~/mods/stream-lua-nginx-module
```

```sh
uname -a

Linux archserver 5.12.14-arch1-1 #1 SMP PREEMPT Thu, 01 Jul 2021 07:26:06 +0000 x86_64 GNU/Linux
```

**Comment by simpl** [comment]
This isn't a bug with the NDK module, but by the looks of it, it stems from what files are being used in the configuration file.  

Your Nginx binary is trying to use the shared library file ndk_http_module.so as your configuration file.  The 'ELF' that is referenced is text that is written to the first few bytes of shared libraries, but Nginx is interpreting it as a configuration directive 'ELF', which throws an error because the ELF directive doesn't exist.

What I'm guessing you're doing is that in your config file if you've included the line

```
include mods/ndk_http_module.so
```
instead of
```
load_module mods/ndk_http_module.so;
```
In this case Nginx will be interpreting the NDK shared library as a config file rather than a shared library that it needs to load.

It should be noted that you're adding all your modules with --add-dynamic-module=..., meaning that you're adding them as dynamic modules not static ones.  All modules (I think) can be added statically (using --add-module=...), but only some can be added successfully dynamically.

In general, it's probably best to build all the modules in statically rather than dynamically, and to do this you'd want to change all your --add-dynamic-module to -add-module, and try compiling and testing again.  If you don't, in order to use the modules, you'll need to include a line in your config file for each of those modules you're using.  See the Nginx documentation for more info on this.

If you really want to build some of the modules as dynamic modules, it's probably best to start by compiling all modules statically to start with, and then only include the specific ones you want to compile as dynamic modules.  To be honest, though, in general you're not going to gain much by using dynamic modules IMHO, since the memory overhead of an Nginx binary is small (even with the modules compiled in), and internally modules are only added to the runtime flow if they're actually used in the config file.

You might want to read the last comment about ELFs of [this thread](https://groups.google.com/g/ngx-pagespeed-discuss/c/_4YBZOh-Kdc) also.  It's not quite the same issue, but is comparable.

I'm going to close the issue, but feel free to reply if you're struggling to get it to work.
