### ISSUE TITLE
has new release?

### ISSUE THREAD

**Issue by gdsglgf** [vision5/ngx_devel_kit#33]
Hi,
It has not been released from 2019.
Just wondering whether there is a new release version.

as same as the issue [#26](https://github.com/vision5/ngx_devel_kit/issues/26)

**Comment by simpl** [comment]
@gdsglgf I've just released v0.3.2, which publishes the tag v0.3.2.

The release only had one typo changed since version 0.3.1, and isn't anything that changes anything in the compiled files (just one of the source files).

There's not been active development on this package for years, though bug updates have been applied when they've been highlighted.  There may be active development on it in the future, though no promises.

**Comment by gdsglgf** [comment]
Thanks!
